### ISSUE TITLE
[Chart] Use separate colors for events and suppressed events.

### ISSUE THREAD

**Issue by jfitie** [Vitens/DBM-Desktop#7]
In the chart, both types of events are shown in red right now; I suggest changing the color of suppressed events to e.g. yellow or gray.

**Comment by etrietsch** [comment]
This was actually a bug: suppressed events were shown as events. Fixed in next version

**Comment by jfitie** [comment]
Suppressed events are now not shown at all in the chart. Could we see these in another color (yellow, gray) as suggested?
In the table on the right, suppressed events are still shown in red.

**Comment by etrietsch** [comment]
Fixed and added in new version
